#!/bin/bash
if [ "$#" -gt 1 ]
then
    curl -X POST -b $(dirname $0)/cookies.txt -c $(dirname $0)/cookies.txt -H "Content-Type: application/json" -d '{"pw":"'"$1"'","np":"'"$2"'"}' https://foodloginserver.herokuapp.com/api/change
else
    echo "change password needs old password and new password as arguments"
fi
