#!/bin/bash
if [ "$#" -gt 1 ]
then
	curl -D ./headers.txt -c ./cookies.txt -H "Content-Type: application/json" -d '{"em":"'"$1"'","pw":"'"$2"'"}' https://foodloginserver.herokuapp.com/login
else
	echo "login needs email address and password as arguments"
fi