#!/bin/bash
if [ "$#" -gt 1 ]
then
	curl -c ./cookies.txt -H "Content-Type: application/json" -d '{"sg":"pza00mul086p578chox5hf0eyjtyvxh63bjrwnfcab82f6yuk4t","em":"'"$1"'","pw":"'"$2"'"}' https://foodloginserver.herokuapp.com/login
else
	echo "login needs email address and password as arguments"
fi