#!/bin/bash
if [ "$#" -gt 0 ]
then
    curl -X POST -H "Content-Type: application/json" -d '{"sg":"pza00mul086p578chox5hf0eyjtyvxh63bjrwnfcab82f6yuk4t","em":"'"$1"'"}' https://foodloginserver.herokuapp.com/api/reset
else
    echo "reset password needs email address as argument"
fi

